### ISSUE TITLE
Depositing to Invenio without a license in metadata gives traceback

### ISSUE THREAD

**Issue by poikilotherm** [hermes-hmc/workflow#164]
Here's what happens:

```
hermes deposit --auth-token *** --file showcase.zip --file README.md
hermes workflow (0.1.0)
=======================

Workflow to publish research software with rich metadata

# Running Hermes
Running Hermes command line in: /home/runner/work/showcase/showcase
Metadata deposition
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/bin/hermes", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/hermes/cli.py", line 103, in invoke
    return super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/hermes/commands/workflow.py", line 190, in deposit
    deposit_preparator(click_ctx, ctx)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/hermes/commands/deposit/invenio.py", line 68, in prepare_deposit
    license = _get_license_identifier(ctx, licenses_api_url)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/hermes/commands/deposit/invenio.py", line 426, in _get_license_identifier
    raise RuntimeError("The given license must be of type str")
RuntimeError: The given license must be of type str
```

Here's the `process/codemeta.json` file for [hermes-hmc/showcase@8d9ed45b0d](https://github.com/hermes-hmc/showcase/commit/8d9ed45b0da7120749ea8e7712728909fc77fc2a) - there is no license present yet:

```
{
  "@context": [
    "https://doi.org/10.5063/schema/codemeta-2.0",
    {
      "hermes": "https://software-metadata.pub/ns/hermes/"
    }
  ],
  "@type": "SoftwareSourceCode",
  "author": [
    {
      "@id": "http://orcid.org/0000-0001-9338-6966",
      "@type": "Person",
      "affiliation": {
        "@type": "Organization",
        "legalName": "Jedi Temple Coruscant"
      },
      "familyName": "Tano",
      "givenName": "Ahsoka"
    }
  ],
  "name": "HERMES Showcase",
  "contributor": [
    {
      "@type": "Person",
      "name": "Oliver Bertuch",
      "email": "poikilotherm@users.noreply.github.com",
      "contactPoint": [
        {
          "@type": "ContactPoint",
          "email": "o.bertuch@fz-juelich.de"
        }
      ],
      "hermes:contributionRole": [
        {
          "@type": "Role",
          "roleName": "git author",
          "startTime": "2022-08-10T10:25:49+02:00",
          "endTime": "2023-05-03T10:16:05+02:00"
        },
        {
          "@type": "Role",
          "roleName": "git committer",
          "startTime": "2022-08-10T10:25:49+02:00",
          "endTime": "2023-05-03T10:16:05+02:00"
        }
      ]
    },
    {
      "@type": "Person",
      "name": "GitHub",
      "email": "noreply@github.com",
      "hermes:contributionRole": [
        {
          "@type": "Role",
          "roleName": "git committer",
          "startTime": "2022-08-10T10:25:49+02:00",
          "endTime": "2023-05-03T10:16:05+02:00"
        }
      ]
    }
  ],
  "hermes:gitBranch": "main"
}%  
```

**Comment by zyzzyxdonta** [comment]
I understand what is happening. What would be the correct thing to do here? Currently, hermes can only do depositions with `"access_right": "open"` and this requires the deposit to have a license. Do we want to allow `closed` access depositions or do we require the user to provide a license?

**Comment by zyzzyxdonta** [comment]
Consensus is: This needs to be configurable
